# Generated by Django 4.0.2 on 2022-03-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email_adrs', models.EmailField(max_length=200)),
                ('suggestions', models.CharField(max_length=200)),
                ('date_time', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='mainpageinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptm1', models.CharField(max_length=200)),
                ('symptm2', models.CharField(max_length=200)),
                ('symptm3', models.CharField(max_length=200)),
                ('symptm4', models.CharField(max_length=200)),
                ('symptm5', models.CharField(max_length=200)),
                ('Disease', models.CharField(max_length=200, null=True)),
                ('date_time', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'mainpageinfo',
            },
        ),
    ]
